{{- if .Values.pullSecret.token }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "{{ template "ibm-mcm.fullname" . }}-regcred"
  labels:
    app: {{ template "ibm-mcm.name" . }}
    chart: {{ template "ibm-mcm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  .dockerconfigjson: "{{ .Values.pullSecret.token }}"
{{- end }}

