apiVersion: v1
entries:
  ibm-mcm-prod:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-28T10:47:34.430564056-06:00
    description: IBM Multi-cloud Manager
    digest: 4cd4a82772f39b053341171c0e960a4a5a8c48df348dd611fb53cce70db7ed98
    name: ibm-mcm-prod
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/mcm-openshift-charts/master/charts/ibm-mcm-prod-3.1.1.tgz
    version: 3.1.1
  ibm-mcmk-prod:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-11-28T10:47:34.43723341-06:00
    description: IBM Multi-Cloud Manager Klusterlet
    digest: c577013103519345367093ddd7dbfe5482fa03e40be2a0beb2e41d856c42ae55
    keywords:
    - ICP
    - Analytics
    - deploy
    - Commercial
    - amd64
    name: ibm-mcmk-prod
    tillerVersion: '>=2.7.3'
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/mcm-openshift-charts/master/charts/ibm-mcmk-prod-3.1.1.tgz
    version: 3.1.1
generated: 2018-11-28T10:47:34.422816658-06:00
