{{- if .Values.controller.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "ibm-mcm.fullname" . }}-grafana-predelete"
  labels:
    app: {{ template "ibm-mcm.name" . }}
    chart: {{ template "ibm-mcm.chart" . }}
    component: "mcmui"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-grafana-predelete"
      labels:
        app: {{ template "ibm-mcm.name" . }}
        chart: {{ template "ibm-mcm.chart" . }}
        component: "mcmui"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "{{ .Values.controller.repository }}:{{ .Values.controller.tag }}"
        imagePullPolicy: "{{ .Values.controller.pullPolicy }}"
        command:
          - "/dsloader"
          - "--prometheus-subpath=mcm-monitor"
          - "unload"
      {{- if .Values.pullSecret.token }}
      imagePullSecrets:
      - name: "{{ template "ibm-mcm.fullname" . }}-regcred"
      {{- end }}
{{- end }}
