{{- if .Values.controller.enabled }}
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "ibm-mcm.fullname" . }}-controller
  labels:
    app: {{ template "ibm-mcm.name" . }}
    chart: {{ template "ibm-mcm.chart" . }}
    component: "mcm-controller"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ibm-mcm.name" . }}
      component: "mcm-controller"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ibm-mcm.name" . }}
        component: "mcm-controller"
        release: {{ .Release.Name }}
      annotations:
        productName: "IBM Multi-cloud Manager - Server"
        productID: "317a72a4f22645aaa1b7a07a83c60af5"
        productVersion: "3.1.1"
    spec:
      containers:
      - name: mcm-controller
        image: "{{ .Values.controller.repository }}:{{ .Values.controller.tag }}"
        imagePullPolicy: {{ .Values.controller.pullPolicy }}
        args:
          - "/mcm-controller"
          - "--enable-cluster-bootstrap"
          - "--enable-rbac"
          - "--enable-federated-prometheus"
          - "--auto-approve-clusterjoinrequest={{ .Values.controller.enableClusterAutoApprove }}"
          - "--prometheus-deployment={{ .Release.Namespace }}/{{ template "ibm-mcm.fullname" . }}-prometheus"
          - "--prometheus-configmap={{ .Release.Namespace }}/{{ template "ibm-mcm.fullname" . }}-prometheus"
      # from here on we define all the compliance controllers
      {{- if .Values.compliance.enabled }}
      - name: propagator-controller
        image: "{{ .Values.compliance.repository }}:{{ .Values.compliance.tag }}"
        imagePullPolicy: "{{ .Values.compliance.pullPolicy }}"
        command: ["propagator-controller"]
        args:
          - "-logtostderr=true"
          - "-v={{ .Values.logLevel }}"
          {{- if (.Values.compliance.mcmNamespace) }}
          - "-mcm-ns={{ .Values.compliance.mcmNamespace }}"
          {{- else }}
          - "-mcm-ns={{ .Release.Namespace }}"
          {{- end }}
      {{- end }}
      # mcm-application contorller
      {{- if .Values.application.enabled }}
      - name: mcm-application
        image: "{{ .Values.application.repository }}:{{ .Values.application.tag }}"
        imagePullPolicy: {{ .Values.application.pullPolicy }}
        args:
          - "/mcm-application"
          {{- if (.Values.compliance.mcmNamespace) }}
          - "--compliance-watch-namespace={{ .Values.compliance.mcmNamespace }}"
          {{- else }}
          - "--compliance-watch-namespace={{ .Release.Namespace }}"
          {{- end }}
      {{- end }}
      {{- if .Values.pullSecret.token }}
      imagePullSecrets:
      - name: "{{ template "ibm-mcm.fullname" . }}-regcred"
      {{- end }}
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
      {{- if .Values.nodeSelector.arch }}
        "beta.kubernetes.io/arch" : {{ .Values.nodeSelector.arch }}  
      {{- end }}
      {{- if .Values.nodeSelector.os }}
        "beta.kubernetes.io/os" : {{ .Values.nodeSelector.os }}
      {{- end }}
      {{- if .Values.nodeSelector.customLabelSelector }}
        {{ .Values.nodeSelector.customLabelSelector }} : {{ .Values.nodeSelector.customLabelValue}}
      {{- end }}
      {{- end }}
{{- end }}
