{{- if .Values.apiserver.enabled }}
{{- $cn := include "ibm-mcm.fullname" . -}}
{{- $ca := genCA "ibm-mcm-ca" 3650 }}
{{- $fqdn := printf "%s.%s" $cn .Release.Namespace }}
{{- $fqdn2 := printf "%s.svc" $fqdn }}
{{- $cert := genSignedCert $cn nil (list $fqdn $fqdn2) 3650 $ca }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "ibm-mcm.fullname" . }}-apiserver-secrets
#  namespace: kube-system
  labels:
    app: {{ template "ibm-mcm.name" . }}
    chart: {{ template "ibm-mcm.chart" . }}
    release: {{ .Release.Name }}
    component: "apiserver"
data:
  ca.crt: {{ b64enc $ca.Cert }}
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}

---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.mcm.ibm.com
spec:
  group: mcm.ibm.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "ibm-mcm.fullname" . }}
  caBundle: {{ b64enc $ca.Cert }}
  priority: 1
  groupPriorityMinimum: 10000
  versionPriority: 20

---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.clusterregistry.k8s.io
spec:
  group: clusterregistry.k8s.io
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "ibm-mcm.fullname" . }}
  caBundle: {{ b64enc $ca.Cert }}
  priority: 1
  groupPriorityMinimum: 10000
  versionPriority: 20
{{- end }}
