{{- if .Values.apiserver.enabled }}
{{- $ca := genCA "ibm-mcm-etcd" 3650 }}
{{- $cn := include "ibm-mcm.fullname" . -}}
{{- $cert := genSignedCert $cn (list "127.0.0.1") nil 3650 $ca }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "ibm-mcm.fullname" . }}-etcd-secrets
  labels:
    app: {{ template "ibm-mcm.name" . }}
    chart: {{ template "ibm-mcm.chart" . }}
    release: {{ .Release.Name }}
    component: "apiserver"
data:
  ca.crt: {{ b64enc $ca.Cert }}
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
{{- end }}
