{{- if .Values.apiserver.enabled }}
kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{ template "ibm-mcm.name" . }}
    chart: {{ template "ibm-mcm.chart" . }}
    component: "mcm-apiserver"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "ibm-mcm.fullname" . }}
spec:
  selector:
    app: {{ template "ibm-mcm.name" . }}
    component: "mcm-apiserver"
    release: {{ .Release.Name }}
  ports:
  - name: secure
    protocol: TCP
    port: 443
    targetPort: 443
{{- end }}
