{{- if .Values.console.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ibm-mcm.fullname" . }}-mcmui
  labels:
    app: {{ template "ibm-mcm.name" . }}
    chart: {{ template "ibm-mcm.chart" . }}
    component: "mcmui"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ibm-mcm.name" . }}
      component: "mcmui"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ibm-mcm.name" . }}
        component: "mcmui"
        release: {{ .Release.Name }}
      annotations:
        productName: "IBM Multi-cloud Manager - Server"
        productID: "317a72a4f22645aaa1b7a07a83c60af5"
        productVersion: "3.1.1"
    spec:
      containers:
      - name: hcm-ui
        image: "{{ .Values.console.mcmui.image.repository }}:{{ .Values.console.mcmui.image.tag }}"
        imagePullPolicy: {{ .Values.console.mcmui.image.pullPolicy }}
        env:
        - name: hcmUiApiUrl
          value: https://{{ template "ibm-mcm.fullname" . }}-mcmuiapi:4000/hcmuiapi
        - name: cfcRouterUrl
          value: https://icp-management-ingress:8443
        - name: PLATFORM_IDENTITY_PROVIDER_URL
          value: https://icp-management-ingress:8443/idprovider
        - name: WLP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: WLP_CLIENT_ID
              name: platform-oidc-credentials
        - name: WLP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: WLP_CLIENT_SECRET
              name: platform-oidc-credentials
        ports:
        - containerPort: 3000
          protocol: TCP
      {{- if .Values.pullSecret.token }}
      imagePullSecrets:
      - name: "{{ template "ibm-mcm.fullname" . }}-regcred"
      {{- end }}
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
      {{- if .Values.nodeSelector.arch }}
        "beta.kubernetes.io/arch" : {{ .Values.nodeSelector.arch }}  
      {{- end }}
      {{- if .Values.nodeSelector.os }}
        "beta.kubernetes.io/os" : {{ .Values.nodeSelector.os }}
      {{- end }}
      {{- if .Values.nodeSelector.customLabelSelector }}
        {{ .Values.nodeSelector.customLabelSelector }} : {{ .Values.nodeSelector.customLabelValue}}
      {{- end }}
      {{- end }}
{{- end }}
