{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ibm-mcm.fullname" . }}-mcmuiapi
  labels:
    app: {{ template "ibm-mcm.name" . }}
    component: "mcmuiapi"
    chart: {{ template "ibm-mcm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: {{ template "ibm-mcm.name" . }}
    component: "mcmuiapi"
    release: {{ .Release.Name }}
{{- end }}
