{{- if .Values.klusterlet.enabled }}
{{- if .Values.klusterlet.apiserverConfig.server }}
{{- $config := printf `
apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: %s
  name: hcm-cluster
contexts:
- context:
    cluster: hcm-cluster
    user: klusterlet
  name: hcm-cluster-context
current-context: hcm-cluster-context
users:
- name: klusterlet
  user:
    token: %s` .Values.klusterlet.apiserverConfig.server .Values.klusterlet.apiserverConfig.token }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ibm-mcm.fullname" . }}-klusterlet
  labels:
    app: {{ template "ibm-mcm.name" . }}
    chart: {{ template "ibm-mcm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config: {{ b64enc $config }}
{{- end }}
{{- end }}
