{{- if .Values.prometheus.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "ibm-mcm.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    release: {{ .Release.Name }}
  name: {{ template "ibm-mcm.fullname" . }}-prometheus-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.prometheus.persistentVolume.size }}"
{{- if .Values.prometheus.persistentVolume.storageClass }}
{{- if (eq "-" .Values.prometheus.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.prometheus.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
