{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "ibm-mcm.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "ibm-mcm.fullname" . }}-prometheus
data:
{{ include "prometheusConfig" . | indent 2 }}

{{- end -}}
