{{ if .Values.topology.enabled }}
---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: {{ template "ibm-mcm.fullname" . }}-weave-basicauth-secret
      labels:
        app: {{ template "ibm-mcm.name" . }}
        chart: {{ template "ibm-mcm.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      component: "weave-scope-secret"
    data:
      username: {{ b64enc .Values.topology.username }}
      password: {{ b64enc .Values.topology.password }}
  - apiVersion: apps/v1beta1
    kind: Deployment
    metadata:
      name: {{ template "ibm-mcm.fullname" . }}-weave-scope-app
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxMCIsIEdpdFZlcnNpb246InYxLjEwLjAiLCBHaXRDb21taXQ6ImZjMzJkMmYzNjk4ZTM2YjkzMzIyYTM0NjVmNjNhMTRlOWYwZWFlYWQiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTAzLTI3VDAwOjEzOjAyWiIsIEdvVmVyc2lvbjoiZ28xLjkuNCIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJkYXJ3aW4vYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjEwIiwgR2l0VmVyc2lvbjoidjEuMTAuMCtpY3AtZWUiLCBHaXRDb21taXQ6IjljYjY0ZGU0Y2E0ZDAzOWMzNWY0YTI5NzIxYWE1Y2Y3ODc2NDhhMTUiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTA0LTI3VDA2OjMyOjE4WiIsIEdvVmVyc2lvbjoiZ28xLjkuMyIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJsaW51eC9hbWQ2NCJ9Cg==",
              "date": "Tue May 08 2018 17:14:07 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-scope-app
        app: {{ template "ibm-mcm.name" . }}
        chart: {{ template "ibm-mcm.chart" . }}
        component: "weave-scope-app"
      namespace: kube-system
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      template:
        metadata:
          labels:
            name: weave-scope-app
            app: {{ template "ibm-mcm.name" . }}
            chart: {{ template "ibm-mcm.chart" . }}
            component: "weave-scope-app"
          annotations:
            productName: "IBM Multi-cloud Manager - Klusterlet"
            productID: "354b8990aab44c9988a0edfda101b128"
            productVersion: "3.1.1"
        spec:
          containers:
            - name: router
              image: {{ .Values.router.image.repository }}:{{ .Values.router.image.tag }}
              command: ["/opt/ibm/router/entry/entrypoint.sh"]
              ports:
              - name: router
                containerPort: 8080
              volumeMounts:
                - mountPath: "/opt/ibm/router/conf"
                  name: weavescope-router-config
                - mountPath: "/opt/ibm/router/certs"
                  name: weavescope-server-certs
                - mountPath: "/opt/ibm/router/client-certs"
                  name: weavescope-ca-secret
                - mountPath: "/opt/ibm/router/entry"
                  name: weavescope-router-entry          
            - name: app
              args:
                - '--mode=app'
              command:
                - /home/weave/scope
              env: 
              {{ if .Values.topology.enableAuth }}
              - name: BASICAUTH_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: {{ template "ibm-mcm.fullname" . }}-weave-basicauth-secret
                    key: username
              - name: BASICAUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ template "ibm-mcm.fullname" . }}-weave-basicauth-secret
                    key: password
              {{ else }}
              - name: DISABLE_BASICAUTH
                value: true
              {{ end }}
              image: "{{ .Values.topology.weave.image.repository }}:{{ .Values.topology.weave.image.tag }}"
              imagePullPolicy: {{ .Values.topology.weave.image.pullPolicy }}
              ports:
                - containerPort: 4040
                  protocol: TCP
          {{- if .Values.pullSecret.token }}
          imagePullSecrets:
          - name: "{{ template "ibm-mcm.fullname" . }}-regcred"
          {{- end }}
          volumes:
            - name: weavescope-router-config
              configMap:
                name: {{ template "ibm-mcm.fullname" . }}-weavescope-router-nginx-config
            - name: weavescope-ca-secret
              secret:
                secretName: {{ template "ibm-mcm.fullname" . }}-weavescope-ca-secrets
            - name: weavescope-server-certs
              secret:
                secretName: {{ template "ibm-mcm.fullname" . }}-weavescope-client-secrets
            - name: weavescope-router-entry
              configMap:
                name: {{ template "ibm-mcm.fullname" . }}-weavescope-router-entry-config
                defaultMode: 0744
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ template "ibm-mcm.fullname" . }}-weave-scope
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxMCIsIEdpdFZlcnNpb246InYxLjEwLjAiLCBHaXRDb21taXQ6ImZjMzJkMmYzNjk4ZTM2YjkzMzIyYTM0NjVmNjNhMTRlOWYwZWFlYWQiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTAzLTI3VDAwOjEzOjAyWiIsIEdvVmVyc2lvbjoiZ28xLjkuNCIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJkYXJ3aW4vYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjEwIiwgR2l0VmVyc2lvbjoidjEuMTAuMCtpY3AtZWUiLCBHaXRDb21taXQ6IjljYjY0ZGU0Y2E0ZDAzOWMzNWY0YTI5NzIxYWE1Y2Y3ODc2NDhhMTUiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTA0LTI3VDA2OjMyOjE4WiIsIEdvVmVyc2lvbjoiZ28xLjkuMyIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJsaW51eC9hbWQ2NCJ9Cg==",
              "date": "Tue May 08 2018 17:14:07 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: {{ template "ibm-mcm.fullname" . }}-weave-scope-app
        app: {{ template "ibm-mcm.name" . }}
        chart: {{ template "ibm-mcm.chart" . }}
        component: "weave-scope-app"
      namespace: kube-system
    spec:
      ports:
        - name: app
          port: 443
          protocol: TCP
          targetPort: 8443
      selector:
        app: {{ template "ibm-mcm.name" . }}
        chart: {{ template "ibm-mcm.chart" . }}
        component: "weave-scope-app"
  - apiVersion: extensions/v1beta1
    kind: DaemonSet
    metadata:
      name: {{ template "ibm-mcm.fullname" . }}-weave-scope
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "original-request": {
              "url": "/k8s/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxMCIsIEdpdFZlcnNpb246InYxLjEwLjAiLCBHaXRDb21taXQ6ImZjMzJkMmYzNjk4ZTM2YjkzMzIyYTM0NjVmNjNhMTRlOWYwZWFlYWQiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTAzLTI3VDAwOjEzOjAyWiIsIEdvVmVyc2lvbjoiZ28xLjkuNCIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJkYXJ3aW4vYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjEwIiwgR2l0VmVyc2lvbjoidjEuMTAuMCtpY3AtZWUiLCBHaXRDb21taXQ6IjljYjY0ZGU0Y2E0ZDAzOWMzNWY0YTI5NzIxYWE1Y2Y3ODc2NDhhMTUiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE4LTA0LTI3VDA2OjMyOjE4WiIsIEdvVmVyc2lvbjoiZ28xLjkuMyIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJsaW51eC9hbWQ2NCJ9Cg==",
              "date": "Tue May 08 2018 17:14:07 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
      labels:
        name: weave-scope
        app: {{ template "ibm-mcm.name" . }}
        chart: {{ template "ibm-mcm.chart" . }}
        component: "weave-scope"
      namespace: kube-system
    spec:
      minReadySeconds: 5
      template:
        metadata:
          labels:
            name: weave-scope
            app: {{ template "ibm-mcm.name" . }}
            chart: {{ template "ibm-mcm.chart" . }}
            component: "weave-scope"
          annotations:
            productName: "IBM Multi-cloud Manager - Klusterlet"
            productID: "354b8990aab44c9988a0edfda101b128"
            productVersion: "3.1.1"
        spec:
          containers:
            - name: scope-agent
              args:
                - '--mode=probe'
                - '--probe.docker.bridge=docker0'
                - '--probe.docker=true'
                - '--probe.kubernetes=true'
                - '--probe.insecure=true'
                - '{{ template "ibm-mcm.fullname" . }}-weave-scope.kube-system.svc.cluster.local:443'
              command:
                - /home/weave/scope
              env:
                {{ if .Values.topology.enableAuth }}
                - name: BASICAUTH_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "ibm-mcm.fullname" . }}-weave-basicauth-secret
                      key: username
                - name: BASICAUTH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "ibm-mcm.fullname" . }}-weave-basicauth-secret
                      key: password
                {{ else }}
                - name: DISABLE_BASICAUTH
                  value: true
              {{ end }}
                - name: KUBERNETES_HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              image: "{{ .Values.topology.weave.image.repository }}:{{ .Values.topology.weave.image.tag }}"
              imagePullPolicy: {{ .Values.topology.weave.image.pullPolicy }}
              securityContext:
                privileged: true
              volumeMounts:
                - name: docker-socket
                  mountPath: /var/run/docker.sock
                - name: scope-plugins
                  mountPath: /var/run/scope/plugins
                - name: sys-kernel-debug
                  mountPath: /sys/kernel/debug
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: true
          hostPID: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
          volumes:
            - name: docker-socket
              hostPath:
                path: /var/run/docker.sock
            - name: scope-plugins
              hostPath:
                path: /var/run/scope/plugins
            - name: sys-kernel-debug
              hostPath:
                path: /sys/kernel/debug
          {{- if .Values.pullSecret.token }}
          imagePullSecrets:
          - name: "{{ template "ibm-mcm.fullname" . }}-regcred"
          {{- end }}
      updateStrategy:
        type: RollingUpdate
{{ end }}
